== Ödev-07

=== Command Pattern

Bu örnekte bir satranç oyunundaki at ve piyon taşlarının nasıl hareket ettiği gösterilmektedir. Bu örnek yapılırken Command Pattern kullanılmıştır.

TasCommand sınıfı ile sadece ileri, geri, sağa ve sola gitme hareketleri tanımlanmıştır.

Atın veya piyonun yapacağı hareketler CompositTasCommand sınıfı kullanılarak belirlenmiştir.

[source, cpp]
----
#include <iostream>
#include <vector>

class Tas{                                                                      // <1>
public:
    int pozisyonX{0};
    int pozisyonY{0};

    Tas(int pozisyonX, int pozisyonY) : pozisyonX(pozisyonX), pozisyonY(pozisyonY) {}

    friend std::ostream &operator<<(std::ostream &os, const Tas &tas) {
        os << "pozisyonX: " << tas.pozisyonX << " pozisyonY: " << tas.pozisyonY;
        return os;
    }
};

class Command{                                                                  // <2>
    virtual void hareketEt() = 0;
};

class TasCommand: public Command{                                               // <3>
public:
    Tas& tas;
    enum Hareket{ileri,geri,saga,sola} hareket;

    TasCommand(Tas &tas, Hareket hareket) : tas(tas), hareket(hareket) {}

    void hareketEt() override {                                                 // <4>
        switch (hareket) {

            case ileri:
                tas.pozisyonY++;
                break;
            case geri:
                tas.pozisyonY--;
                break;
            case saga:
                tas.pozisyonX++;
                break;
            case sola:
                tas.pozisyonX--;
                break;
        }
    }
};

class CompositeTasCommand : public std::vector<TasCommand>, public Command{     // <5>
public:
    CompositeTasCommand(const std::initializer_list<TasCommand> &commands) : vector(commands) {}

    void hareketEt() override {                                                 // <6>
        for(auto cmd : *this)
            cmd.hareketEt();
    }
};

class At : public Tas, public CompositeTasCommand{                              // <7>
public:
    At(int pozisyonX, int pozisyonY)                                            // <8>
            : Tas(pozisyonX, pozisyonY),
              CompositeTasCommand({
                                          TasCommand(*this, TasCommand::ileri),
                                          TasCommand(*this, TasCommand::ileri),
                                          TasCommand(*this, TasCommand::saga),
                                  }
              ) {}
};

class Piyon : public Tas, public CompositeTasCommand{                           // <9>
public:
    Piyon(int pozisyonX, int pozisyonY)                                         // <10>
            : Tas(pozisyonX, pozisyonY),
              CompositeTasCommand({
                                          TasCommand(*this, TasCommand::ileri)
                                  }
              ) {}
};

int main()
{
    At a{1,0};
    Piyon p{4,1};
    std::cout << a << std::endl;
    std::cout << p << std::endl;
    a.hareketEt();
    p.hareketEt();
    std::cout << a << std::endl;
    std::cout << p << std::endl;
    return 0;
}
----
<1> Tas sınıfının tanımlanması. Buradaki *friend std::ostream &operator<<(std::ostream &os, const Tas &tas)* fonksiyonu ile taşın pozisyonu kolayca ekrana basılabiliyor.
<2> Command sınfının tanımlanması.
<3> TasCommand sınıfının tanımlanması. Bu sınıf ile taşın ileri, geri, sağa ve sola girme hareketleri gerçekleştirilir. CompositeTasCommand sınıfında kullanılmak üzere oluşturulmuştur.
<4> hareketEt override edilmesi. Bu fonksiyon ile hareketlerin pozisyonları nasıl etkileyeceği anlaşılmıştır. Her yöne sadece bir birim gidilmektedir.
<5> CompositeTasCommand sıfının tanımlanması. Bu sınıf bir dizi komutun tek fonksiyon ile çalışmasını sağlar.
<6> hareketEt fonksiyonunun override edilmesi. Dizide bulunan bütün komutların çalıştırılmasını sağlar.
<7> At sınıfının tanımlanması.
<8> At sınıfının constructor'ının tanımlanması. Bu fonksiyonda atın nasıl hareket etmesi gerektiği anlatılmaktadır.
<9> Piyon sınıfının tanımlanması.
<10> Piyon sınıfının constructor'ının tanımlanması. Bu fonksiyonda piyonun nasıl hareket etmesi gerektiği anlatılmaktadır.

==== UML Diagramı

[plantuml, Command, png]
----
Class Tas{
    +int pozisyonX
    +int pozisyonY
    +Tas(int pozisyonX, int pozisyonY)
}

Interface Command{
    +{abstract} void hareketEt()
}

Class TasCommand{
    +Tas tas
    +enum Hareket{ileri,geri,saga,sola} hareket
    +void hareketEt()
}

Class CompositeTasCommand{
    +CompositeTasCommand(const std::initializer_list<TasCommand> &commands)
    +void hareketEt()
}

Class At{
    +At(int pozisyonX, int pozisyonY)
}

Class Piyon{
    +Piyon(int pozisyonX, int pozisyonY)
}

Command <|. TasCommand
TasCommand <--- CompositeTasCommand : Kullanır
Command <|... CompositeTasCommand
Tas <|-- At
Tas <|-- Piyon
CompositeTasCommand <|-- At
CompositeTasCommand <|-- Piyon
TasCommand <--- At : Kullanılır
TasCommand <--- Piyon : Kullanır
TasCommand o--- Tas
----

