== Ödev-08

=== Decorator Pattern

Bu örnekte bir oyundaki savaşçı ve düşmana zırh ve silah eklemsinin nasıl yapıldığı anlatılmaktadır. Bu örnek yapılırken
Decorator Pattern kullanılmıştır.

Savaşçı ve Düşman sınıflarına ekleme yapabilmek için SilahEklentisi ve ZırhEklentisi sınıfları kullanılmaktadır.

[source,cpp]
----
#include <iostream>

class Karakter                          // <1>
{
public:
    virtual void info() = 0;
};

class Savasci : public Karakter         // <2>
{
private:
    std::string isim;
    int can;

public:
    Savasci() {}                        // <3>
    Savasci(const std::string &isim, int can) : isim(isim), can(can){}

    void info() override {
        std::cout << "Savascinin " << std::endl
                  << "İsmi: " << isim << std::endl
                  << "Cani: " << can << std::endl;
    }
};

class Dusman : public Karakter{         // <4>
private:
    int can;

public:
    Dusman() {}
    Dusman(int can) : can(can) {}

    void info() override {              // <5>
        std::cout << "Dusmanin " << std::endl
                  << "Cani: " << can << std::endl;
    }

};

class SilahEklentisi : public Karakter{ // <6>
private:
    Karakter& karakter;
    int hasarGucu;
    std::string silahTipi;

public:
    SilahEklentisi(Karakter &karakter, int hasarGucu, const std::string &silahTipi) : karakter(karakter),
                                                                                      hasarGucu(hasarGucu),
                                                                                      silahTipi(silahTipi) {}

    void info() override {              // <7>
        karakter.info();
        std::cout << "Hasar Gucu: " << hasarGucu << std::endl
                  << "Silah Tipi: " << silahTipi << std::endl;
    }
};

class ZirhEklentisi : public Karakter{  // <8>
private:
    Karakter& karakter;
    int koruma;

public:

    ZirhEklentisi(Karakter &karakter, int koruma) : karakter(karakter), koruma(koruma) {}

    void info() override {              // <9>
        karakter.info();
        std::cout << "Koruma: " << koruma << std::endl;
    }
};

int main()
{
    Savasci s1("Kemal",100);
    SilahEklentisi ss1(s1,50,"Kilic");
    ZirhEklentisi ssz1(ss1,100);

    Dusman d1(50);
    SilahEklentisi ds1(d1,25,"Bicak");
    ZirhEklentisi dsz1(ds1,25);

    ssz1.info();
    std::cout << std::endl;
    dsz1.info();

    return 0;
}
----
<1> Karakter arayüzünün tanımlanması. Savaşçı ve Düşman sınıfları bu sınıf kullanılarak oluşturulur.
<2> Savaşçı sınıfının tanımlanması.
<3> Savaşçı sınıfının temel bilgilerini yazan fonksiyonun tanımlanması.
<4> Düşman sınıfının tanımlanması.
<5> Savaşçı sınıfının temel bilgilerini yazan fonksiyonun tanımlanması.
<6> Silah Eklentisi sınıfının tanımlanması.
<7> Karakterdeki mevcut bilgilere ek olarak hasar gücü ve silih tipini yazan fonksiyondur.
<8> Zırh Eklentisi sınıfının tanımlanması.
<9> Karakterdeki mevcut bilgilere ek olarak korumayı yazan fonksiyondur.

*Program Çıktısı*
----
Savascinin
İsmi: Kemal
Cani: 100
Hasar Gucu: 50
Silah Tipi: Kilic
Koruma: 100

Dusmanin
Cani: 50
Hasar Gucu: 25
Silah Tipi: Bicak
Koruma: 25
----

==== UML Diagramı

[plantuml, Decorator, png]
----
Interface Karakter
{
    +{abstract} void info()
}

class Savaşçı
{
    -string isim;
    -int can;

    +Savasci()
    +Savasci(string &isim, int can)
    +void info()
}

class Düşman
{
    -int can;

    +Dusman()
    +Dusman(int can)
    +void info()
}

class SilahEklentisi
{
    -Karakter karakter;
    -int hasarGucu;
    -string silahTipi;

    +SilahEklentisi(Karakter karakter, int hasarGucu, string &silahTipi)
    +void info()
}

class ZırhEklentisi
{
    -Karakter karakter;
    -int koruma;

    +ZırhEklentisi(Karakter karakter, int koruma)
    +void info()
}

Karakter <|... Savaşçı
Karakter <|... Düşman
SilahEklentisi o-- Karakter
ZırhEklentisi o-- Karakter
Karakter <|.. SilahEklentisi
Karakter <|.. ZırhEklentisi
----

